name: taillz
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter  
  cupertino_icons: ^1.0.2
  easy_localization: ^3.0.0
  flutter_svg: any
  avatar_view: ^1.0.0+3
  google_fonts: ^2.1.0
  video_player: ^2.2.11
  flick_video_player: ^0.3.1
  volume: ^1.0.1
  flutter_colorpicker: ^1.0.2
  email_validator: ^2.0.1
  another_flushbar: ^1.10.28
  get: ^4.6.1



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.0.3+1
  flutter_launcher_icons: ^0.9.2
flutter_icons:
  ios: true
  android: true
  image_path: "assets/images/icon.png"
  adaptive_icon_foreground: "assets/images/1024.png"
  adaptive_icon_background: "assets/images/1024.png"

flutter_native_splash:

  image: assets/images/splash.png
  android: true
  ios: true
  android_gravity: fill
  ios_content_mode: scaleAspectFill



flutter:

  uses-material-design: true


  assets:
   - assets/icons/female/
   - assets/icons/male/
   - assets/icons/
   - assets/icons/logo_text.svg
   - assets/images/
   - assets/images/consult/
   - assets/images/background.jpg
   - assets/videos/
   - assets/translations/
   - assets/translations/en.json
   - assets/translations/he.json


  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Black.ttf
        - asset: assets/fonts/Montserrat-Bold.ttf
        - asset: assets/fonts/Montserrat-ExtraBold.ttf
        - asset: assets/fonts/Montserrat-Light.ttf
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-SemiBold.ttf
